language: python
matrix:
  fast_finish: true
  include:
    - env: BOARD="d1_mini"
    - env: BOARD="esp01"
    - env: BOARD="nodemcuv2"
  allow_failures:
    - env: BOARD="esp01"
before_install:
  - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/develop/scripts/get-platformio.py)"
install:
  - pip install coveralls
  - platformio lib -g install "ESP8266WiFi"
  - platformio lib -g install "DHT sensor library"
  - platformio lib -g install "PubSubClient"
script:
  - coverage run -m platformio ci enviro-node.ino -b $BOARD
after_success:
  - coveralls
