language: python
before_install:
  - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/develop/scripts/get-platformio.py)"
install:
  - platformio lib -g install "ESP8266WiFi"
  - platformio lib -g install "DHT sensor library"
  - platformio lib -g install "PubSubClient"
script:
  - platformio ci enviro-node.ino -b d1_mini
